-- Phase 1 PostgreSQL schema for the Freqtrade AI MVP loop.
-- Scope: strategy generation metadata, strategy versions, Freqtrade backtest
-- task tracking, parsed summary results, and leaderboard scoring.
--
-- Guardrails:
-- - Do not store real API keys or exchange secrets.
-- - Do not store candle rows or trade-level details in PostgreSQL.
-- - Do not create dry-run, live trading, or deployment tables in Phase 1.

CREATE TABLE strategies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    slug VARCHAR(180) NOT NULL UNIQUE,
    description TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'draft',
    source VARCHAR(64) NOT NULL DEFAULT 'ai_generated',
    tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    current_version_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT strategies_status_check
        CHECK (status IN ('draft', 'active', 'archived')),
    CONSTRAINT strategies_source_check
        CHECK (source IN ('ai_generated', 'imported', 'manual'))
);

CREATE TABLE strategy_generation_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(80) NOT NULL,
    model VARCHAR(160) NOT NULL,
    prompt_hash VARCHAR(128),
    prompt_summary TEXT,
    params_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    requested_count INTEGER NOT NULL DEFAULT 0,
    generated_count INTEGER NOT NULL DEFAULT 0,
    accepted_count INTEGER NOT NULL DEFAULT 0,
    failed_count INTEGER NOT NULL DEFAULT 0,
    error_message TEXT,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT strategy_generation_runs_status_check
        CHECK (status IN ('pending', 'running', 'succeeded', 'failed', 'cancelled')),
    CONSTRAINT strategy_generation_runs_counts_check
        CHECK (
            requested_count >= 0
            AND generated_count >= 0
            AND accepted_count >= 0
            AND failed_count >= 0
        )
);

CREATE TABLE strategy_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_id BIGINT NOT NULL REFERENCES strategies(id) ON DELETE CASCADE,
    generation_run_id BIGINT REFERENCES strategy_generation_runs(id) ON DELETE SET NULL,
    parent_version_id BIGINT REFERENCES strategy_versions(id) ON DELETE SET NULL,
    version_number INTEGER NOT NULL,
    blueprint JSONB NOT NULL,
    generated_code TEXT NOT NULL,
    code_hash VARCHAR(128),
    file_path TEXT NOT NULL,
    validation_status VARCHAR(32) NOT NULL DEFAULT 'pending',
    validation_errors JSONB NOT NULL DEFAULT '[]'::jsonb,
    change_summary TEXT,
    diff_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT strategy_versions_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT strategy_versions_validation_status_check
        CHECK (validation_status IN ('pending', 'passed', 'failed')),
    CONSTRAINT strategy_versions_strategy_version_unique
        UNIQUE (strategy_id, version_number),
    CONSTRAINT strategy_versions_file_path_unique
        UNIQUE (file_path)
);

ALTER TABLE strategies
    ADD CONSTRAINT strategies_current_version_fk
    FOREIGN KEY (current_version_id)
    REFERENCES strategy_versions(id)
    ON DELETE SET NULL;

CREATE TABLE market_data_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exchange VARCHAR(80) NOT NULL,
    pair VARCHAR(80) NOT NULL,
    timeframe VARCHAR(32) NOT NULL,
    data_format VARCHAR(32) NOT NULL,
    relative_path TEXT NOT NULL,
    timerange_start TIMESTAMPTZ,
    timerange_end TIMESTAMPTZ,
    row_count INTEGER,
    file_size_bytes BIGINT,
    checksum VARCHAR(128),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT market_data_files_data_format_check
        CHECK (data_format IN ('feather', 'parquet', 'json', 'csv')),
    CONSTRAINT market_data_files_row_count_check
        CHECK (row_count IS NULL OR row_count >= 0),
    CONSTRAINT market_data_files_size_check
        CHECK (file_size_bytes IS NULL OR file_size_bytes >= 0),
    CONSTRAINT market_data_files_relative_path_unique
        UNIQUE (relative_path),
    CONSTRAINT market_data_files_identity_unique
        UNIQUE (exchange, pair, timeframe, data_format, relative_path)
);

CREATE TABLE backtest_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(180) NOT NULL,
    profile_name VARCHAR(120) NOT NULL,
    config_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    total_tasks INTEGER NOT NULL DEFAULT 0,
    pending_tasks INTEGER NOT NULL DEFAULT 0,
    running_tasks INTEGER NOT NULL DEFAULT 0,
    succeeded_tasks INTEGER NOT NULL DEFAULT 0,
    failed_tasks INTEGER NOT NULL DEFAULT 0,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT backtest_runs_status_check
        CHECK (status IN ('pending', 'running', 'succeeded', 'failed', 'cancelled')),
    CONSTRAINT backtest_runs_counts_check
        CHECK (
            total_tasks >= 0
            AND pending_tasks >= 0
            AND running_tasks >= 0
            AND succeeded_tasks >= 0
            AND failed_tasks >= 0
        )
);

CREATE TABLE backtest_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    backtest_run_id BIGINT NOT NULL REFERENCES backtest_runs(id) ON DELETE CASCADE,
    strategy_version_id BIGINT NOT NULL REFERENCES strategy_versions(id) ON DELETE CASCADE,
    market_data_file_id BIGINT REFERENCES market_data_files(id) ON DELETE SET NULL,
    pair VARCHAR(80) NOT NULL,
    timeframe VARCHAR(32) NOT NULL,
    timerange_start TIMESTAMPTZ,
    timerange_end TIMESTAMPTZ,
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    freqtrade_config_path TEXT,
    result_file_path TEXT,
    error_message TEXT,
    locked_at TIMESTAMPTZ,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT backtest_tasks_status_check
        CHECK (status IN ('pending', 'running', 'succeeded', 'failed', 'cancelled')),
    CONSTRAINT backtest_tasks_identity_unique
        UNIQUE (
            backtest_run_id,
            strategy_version_id,
            pair,
            timeframe,
            timerange_start,
            timerange_end
        )
);

CREATE TABLE backtest_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    backtest_task_id BIGINT NOT NULL UNIQUE REFERENCES backtest_tasks(id) ON DELETE CASCADE,
    strategy_version_id BIGINT NOT NULL REFERENCES strategy_versions(id) ON DELETE CASCADE,
    total_trades INTEGER NOT NULL DEFAULT 0,
    win_rate NUMERIC(10, 6),
    profit_total_abs NUMERIC(20, 8),
    profit_total_pct NUMERIC(12, 6),
    max_drawdown_pct NUMERIC(12, 6),
    sharpe NUMERIC(12, 6),
    sortino NUMERIC(12, 6),
    calmar NUMERIC(12, 6),
    expectancy NUMERIC(20, 8),
    summary JSONB NOT NULL DEFAULT '{}'::jsonb,
    raw_result JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT backtest_results_total_trades_check
        CHECK (total_trades >= 0)
);

CREATE TABLE strategy_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_id BIGINT NOT NULL REFERENCES strategies(id) ON DELETE CASCADE,
    strategy_version_id BIGINT NOT NULL REFERENCES strategy_versions(id) ON DELETE CASCADE,
    backtest_result_id BIGINT REFERENCES backtest_results(id) ON DELETE SET NULL,
    scoring_version VARCHAR(80) NOT NULL,
    total_score NUMERIC(12, 6) NOT NULL,
    profit_score NUMERIC(12, 6),
    risk_score NUMERIC(12, 6),
    stability_score NUMERIC(12, 6),
    quality_score NUMERIC(12, 6),
    metrics_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT strategy_scores_total_score_check
        CHECK (total_score >= 0),
    CONSTRAINT strategy_scores_version_unique
        UNIQUE (strategy_version_id, scoring_version)
);

CREATE TABLE strategy_failure_reasons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_id BIGINT NOT NULL REFERENCES strategies(id) ON DELETE CASCADE,
    strategy_version_id BIGINT NOT NULL REFERENCES strategy_versions(id) ON DELETE CASCADE,
    stage VARCHAR(40) NOT NULL,
    reason_type VARCHAR(80) NOT NULL,
    severity VARCHAR(20) NOT NULL DEFAULT 'error',
    message TEXT NOT NULL,
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT strategy_failure_reasons_stage_check
        CHECK (stage IN ('generation', 'validation', 'static_check', 'backtest_probe')),
    CONSTRAINT strategy_failure_reasons_type_check
        CHECK (
            reason_type IN (
                'blueprint_schema_error',
                'validation_error',
                'render_error',
                'static_policy_violation',
                'backtest_probe_failed',
                'unknown'
            )
        ),
    CONSTRAINT strategy_failure_reasons_severity_check
        CHECK (severity IN ('info', 'warning', 'error'))
);

CREATE INDEX idx_strategies_status ON strategies(status);
CREATE INDEX idx_strategy_generation_runs_status_created
    ON strategy_generation_runs(status, created_at DESC);
CREATE INDEX idx_strategy_versions_strategy_id ON strategy_versions(strategy_id);
CREATE INDEX idx_strategy_versions_generation_run_id ON strategy_versions(generation_run_id);
CREATE INDEX idx_strategy_versions_validation_status ON strategy_versions(validation_status);
CREATE INDEX idx_market_data_files_pair_timeframe
    ON market_data_files(pair, timeframe);
CREATE INDEX idx_market_data_files_exchange_pair_timeframe
    ON market_data_files(exchange, pair, timeframe);
CREATE INDEX idx_backtest_runs_status_created
    ON backtest_runs(status, created_at DESC);
CREATE INDEX idx_backtest_tasks_status_created
    ON backtest_tasks(status, created_at);
CREATE INDEX idx_backtest_tasks_run_status
    ON backtest_tasks(backtest_run_id, status);
CREATE INDEX idx_backtest_tasks_strategy_version
    ON backtest_tasks(strategy_version_id);
CREATE INDEX idx_backtest_results_strategy_version
    ON backtest_results(strategy_version_id);
CREATE INDEX idx_strategy_scores_strategy_id
    ON strategy_scores(strategy_id);
CREATE INDEX idx_strategy_scores_total_score
    ON strategy_scores(total_score DESC, created_at DESC);
CREATE INDEX idx_strategy_failure_reasons_strategy_stage
    ON strategy_failure_reasons(strategy_id, stage, created_at DESC);
CREATE INDEX idx_strategy_failure_reasons_version_type
    ON strategy_failure_reasons(strategy_version_id, reason_type, created_at DESC);

CREATE TABLE local_test_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_key VARCHAR(120) NOT NULL,
    scenario_set VARCHAR(80) NOT NULL,
    source_label VARCHAR(120) NOT NULL,
    environment_label VARCHAR(40) NOT NULL,
    database_url TEXT NOT NULL,
    seed_version VARCHAR(40) NOT NULL,
    batch_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT local_test_batches_environment_check
        CHECK (environment_label IN ('local', 'dev', 'test', 'debug', 'phase8', 'local-test', 'phase8-local')),
    CONSTRAINT local_test_batches_batch_key_unique
        UNIQUE (batch_key)
);

CREATE TABLE local_test_db_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL REFERENCES local_test_batches(id) ON DELETE CASCADE,
    event_type VARCHAR(40) NOT NULL,
    scenario_name VARCHAR(120),
    source_kind VARCHAR(80) NOT NULL,
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT local_test_db_events_type_check
        CHECK (event_type IN ('reset', 'baseline_seed', 'dirty_seed', 'summary'))
);

CREATE INDEX idx_local_test_batches_created
    ON local_test_batches(created_at DESC, id DESC);
CREATE INDEX idx_local_test_db_events_batch
    ON local_test_db_events(batch_id, event_type, scenario_name);
